/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A raw site's cms collection from the database
 */
export interface CmsCollection {
  id: string;
  created_at: string;
  updated_at?: string;
  site_id: string;
  name: string;
  slug: string;
  fields: {
    id: string;
    type:
      | "Email"
      | "Set"
      | "Color"
      | "CommercePropTable"
      | "ItemRefSet"
      | "PlainText"
      | "Video"
      | "Link"
      | "CommercePrice"
      | "RichText"
      | "CommercePropValues"
      | "Number"
      | "EnumOption"
      | "ItemRef"
      | "Bool"
      | "Date"
      | "User"
      | "Phone"
      | "Option"
      | "SubscriptionPlan"
      | "ImageRef"
      | "FileRef";
    slug: string;
    [k: string]: unknown;
  }[];
}
