/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A raw cms item from the database
 */
export interface CmsItem {
  id: string;
  created_at: string;
  updated_at?: string;
  collection_id: string;
  name: string;
  slug: string;
  data?: {
    [k: string]: unknown;
  };
}
