/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A raw event from the database
 */
export interface Event {
  id: string;
  created_at: string;
  updated_at?: string;
  event_type: "click" | "cms" | "form" | "keyboard" | "view";
  css_class?: string;
  css_id?: string;
  value?: string;
  domain?: string;
  site_id: string;
  visitor_id: string;
  path?: string;
  ip_address?: string;
  referer?: string;
  device_id?: string;
  cms_webflow_collection_id?: string;
  cms_webflow_item_id?: string;
  device_client_type?: string;
  device_client_name?: string;
  device_client_version?: string;
  device_client_engine?: string;
  device_client_engine_version?: string;
  device_os_name?: string;
  device_os_version?: string;
  device_os_platform?: string;
  device_type?: string;
  device_brand?: string;
  device_model?: string;
  device_user_agent?: string;
  form_displayed_at?: string;
  form_last_interaction_at?: string;
  form_submitted_at?: string;
  geo_ip_country?: string;
  geo_ip_city?: string;
  geo_ip_latitude?: number;
  geo_ip_longitude?: number;
  geo_ip_region?: string;
  geo_ip_eu?: boolean;
  geo_ip_timezone?: string;
}
