/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A raw metric from the database
 */
export interface Metric {
  id: string;
  dashboard_id?: string;
  created_at: string;
  updated_at: string;
  name: string;
  metric_type: string;
  css_selector?: string;
  path?: string;
  webflow_collection_id?: string;
  cms_collection_id?: string;
  breakdown_by?: string;
  unique_visitor?: boolean;
}
